
spring.datasource.url=jdbc:postgresql://localhost:5432/studynotes
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
app.security.username=${STUDYNOTES_USERNAME}
app.security.password=${STUDYNOTES_PASSWORD}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
