-- Начальная схема: таблицы folders и notes, как их описывают сущности Folder и Note.

CREATE TABLE folders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255),
    parent_id  BIGINT,
    created_at TIMESTAMP(6),
    CONSTRAINT fk_folders_parent FOREIGN KEY (parent_id) REFERENCES folders (id)
);

CREATE TABLE notes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255) NOT NULL,
    content    TEXT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    folder_id  BIGINT,
    CONSTRAINT fk_notes_folder FOREIGN KEY (folder_id) REFERENCES folders (id)
);
